export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const GET_LIST = 'GET_LIST'
export const GET_MY_LIST = 'GET_MY_LIST'